DROP DATABASE IF EXISTS eugescha_db;
CREATE DATABASE IF NOT EXISTS eugescha_db;

USE eugescha_db;

DROP TABLE IF EXISTS T_Photo;
CREATE TABLE IF NOT EXISTS T_Photo (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  thumb_path VARCHAR(255) NOT NULL,
  photo_path VARCHAR(255) NOT NULL,
  upload_date DATE NOT NULL,
  photo_date DATE NOT NULL
)
ENGINE = InnoDB;